### ISSUE TITLE
Client not found (token related error)

### ISSUE THREAD

**Issue by sanjeevverma1** [azai91/alfred-venmo-workflow#1]
It all worked seamlessly until...**Error 244    Client not found** (OAuth/Token Related Error):

![screen shot 2015-12-13 at 10 54 41 pm](https://cloud.githubusercontent.com/assets/7389628/11774681/8a7569f8-a1ec-11e5-8d62-f07740b8c528.png)

I tried all the basics: 1) logging out/logging in via workflow from Alfred, 2) reinstalling Alfred workflow, 3) clearing browser cache, 4) restarting system

If the problem is expired authentication, the solution must be to refresh tokens. From Venmo documentation: "After your access token has expired, you can refresh your tokens by issuing a request to /access_token with your client_id,client_secret and refresh_token." (https://developer.venmo.com/docs/authentication)

Can you set workflow to automatically refresh tokens periodically then re-upload workflow to Git/Packal? 

Thanks @azai91 !!!

**Comment by azai91** [comment]
Hey sanjeevverma1,

My venmo developer keys expired, so I just had to replace them. Try updating the latest version here (https://github.com/azai91/alfred-venmo-workflow/releases). 

If this fixes the solution and you like the workflow, please star this repo (or let me know if you are still an issue)!

Best,
Alex

**Comment by sanjeevverma1** [comment]
Beautiful, works perfectly. Thank you!!

**Comment by drewgbarnes** [comment]
I am getting client not found again..
